# Generated by Django 4.0.4 on 2022-05-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUtils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('url', models.CharField(max_length=2048)),
                ('sec_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('usage', models.IntegerField(default=0)),
                ('extra', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(blank=True, default='OK', max_length=2048, null=True)),
                ('credits', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'APIUtils',
            },
        ),
        migrations.CreateModel(
            name='InvalidName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadEmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(blank=True, max_length=2048, null=True)),
                ('sub_status', models.CharField(blank=True, max_length=2048, null=True)),
                ('free_email', models.BooleanField(blank=True, null=True)),
                ('did_you_mean', models.CharField(blank=True, max_length=2048, null=True)),
                ('account', models.CharField(blank=True, max_length=2048, null=True)),
                ('domain', models.CharField(blank=True, max_length=2048, null=True)),
                ('domain_age_days', models.CharField(blank=True, max_length=2048, null=True)),
                ('smtp_provider', models.CharField(blank=True, max_length=2048, null=True)),
                ('mx_record', models.CharField(blank=True, max_length=2048, null=True)),
                ('mx_found', models.CharField(blank=True, max_length=2048, null=True)),
                ('firstname', models.CharField(blank=True, max_length=2048, null=True)),
                ('lastname', models.CharField(blank=True, max_length=2048, null=True)),
                ('gender', models.CharField(blank=True, max_length=2048, null=True)),
                ('country', models.CharField(blank=True, max_length=2048, null=True)),
                ('region', models.CharField(blank=True, max_length=2048, null=True)),
                ('city', models.CharField(blank=True, max_length=2048, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=2048, null=True)),
                ('processed_at', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadPhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, max_length=2048, null=True)),
                ('Region', models.CharField(blank=True, max_length=2048, null=True)),
                ('CountryCode', models.CharField(blank=True, max_length=2048, null=True)),
                ('Type', models.CharField(blank=True, max_length=2048, null=True)),
                ('Country_Name', models.CharField(blank=True, max_length=2048, null=True)),
                ('Area', models.CharField(blank=True, max_length=2048, null=True)),
                ('Original_Network', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(null=True)),
                ('email_valid', models.BooleanField(null=True)),
                ('name_valid', models.BooleanField(null=True)),
                ('phone_valid', models.BooleanField(null=True)),
                ('email_status', models.CharField(blank=True, max_length=2048, null=True)),
                ('phone_status', models.CharField(blank=True, max_length=2048, null=True)),
                ('name_status', models.CharField(blank=True, max_length=2048, null=True)),
                ('double', models.BooleanField(null=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('lead_email_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='BaziloLeadProcessor.leademailinfo')),
                ('lead_phone_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='BaziloLeadProcessor.leadphoneinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
