name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3


    - name: Run automated deployment
      run: |
        cd ~/app/BaziloFilter
        sudo git pull origin master
        sudo python3 manage.py test

